### ISSUE TITLE
UAC?

### ISSUE THREAD

**Issue by diVineProportion** [master255/Redirector#1]
Why is this installed to %ProgamFiles% ? 
Unless user disables UAC prompts they will have interruption in smooth transition from browser to video player.

May I make suggestions,

- Ask the user if they already have a video player on their pc, even if they don't, inform them about pot player installation (I understand you may have as no english installer) 

- If for some reason you must install to UAC protected directory, suggest this. I use it all the time and it works great [Microsoft Application Compatibility Toolkit / Compatibility Administrator](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install) and example use [Here](https://mynuuo.zendesk.com/hc/en-us/articles/360000764413-How-to-disable-UAC-for-a-specific-program)

**Comment by master255** [comment]
Yes you are right. UAC questions will get in the way. So turn them off! I do not know what they are for. To whom they interfere, can turn them off.
The player installed in the system may give errors. I can not trust him. I make only high-quality software!
Today very few players support this technology. So it makes no sense to make a choice.

Sorry for the long answer. I have not seen your questions.
