### ISSUE TITLE
Only works on http://master255.org

### ISSUE THREAD

**Issue by diVineProportion** [master255/Redirector#2]
How does this work? URI Scheme? redirector:res/movie/ex.avi ??

How is this produced? is it schema like chrome: or magnet: ? Does it use js script?
![image](https://user-images.githubusercontent.com/38984875/40634325-2f969068-62a9-11e8-89a1-1e8b13413031.png)

**Comment by master255** [comment]
It's protocol. My custom protocol. Yes it use js script. You can see code of program.
